### ISSUE TITLE
请求补充文档!

### ISSUE THREAD

**Issue by CberYellowstone** [wopub/Bilibili2Bangumi#1]
关于`Bgm API`部分完全不知道该如何操作
希望能补充文档!

**Comment by nKsnC** [comment]
已更新与调整使用方法

bgm api 只有授权码模式，目前我也没有什么很好的办法，就只能麻烦一下，手动输入

**Comment by CberYellowstone** [comment]
> 已更新与调整使用方法
> 
> bgm api 只有授权码模式，目前我也没有什么很好的办法，就只能麻烦一下，手动输入

回调地址请问该填写什么?

> 另外：我认为可以通过python开启一个本地服务器实现自动获取code
> 把回调地址改成localhost就行

**Comment by CberYellowstone** [comment]
> 已更新与调整使用方法
> 
> bgm api 只有授权码模式，目前我也没有什么很好的办法，就只能麻烦一下，手动输入

![image](https://user-images.githubusercontent.com/37031767/116974897-636b3c00-acf1-11eb-9399-c96eda8c7810.png)
我把获取到的code填写进去之后，发生了此种报错

**Comment by CberYellowstone** [comment]
> 已更新与调整使用方法
> 
> bgm api 只有授权码模式，目前我也没有什么很好的办法，就只能麻烦一下，手动输入

调试启用153行的print之后发现是这里的问题
![image](https://user-images.githubusercontent.com/37031767/116975490-4f740a00-acf2-11eb-93a5-ee64a1ac1475.png)

**Comment by CberYellowstone** [comment]
> 已更新与调整使用方法
> 
> bgm api 只有授权码模式，目前我也没有什么很好的办法，就只能麻烦一下，手动输入

我一路摸下去算了
之后我会写一个文档pr

**Comment by nKsnC** [comment]
> 回调地址请问该填写什么?

回调地址，`http://localhost` 就行，本地起个服务器，可行

> 我把获取到的code填写进去之后，发生了此种报错
> https://user-images.githubusercontent.com/37031767/116975490-4f740a00-acf2-11eb-93a5-ee64a1ac1475.png

应该是回调地址不匹配

**Comment by nKsnC** [comment]
@CberYellowstone 添加了关于回调地址的说明与配置，这也是我的疏忽，十分抱歉

**Comment by CberYellowstone** [comment]
> @CberYellowstone 添加了关于回调地址的说明与配置，这也是我的疏忽，十分抱歉

我之后将会补充文档提交pr并尝试优化code获取逻辑实现自动获取

**Comment by nKsnC** [comment]
> 我之后将会补充文档提交pr并尝试优化code获取逻辑实现自动获取

十分感谢
