### ISSUE TITLE
bug-未预期的报错s

### ISSUE THREAD

**Issue by CberYellowstone** [wopub/Bilibili2Bangumi#16]
![image](https://user-images.githubusercontent.com/37031767/134761637-4fc76989-cd8b-4a5a-8c32-bcaebf6e3476.png)
并发数仅为1
Python 379

**Comment by CberYellowstone** [comment]
问题定位:

**Comment by CberYellowstone** [comment]
py 3.7.9 3.8.10 3.9.5 均复现此bug

**Comment by CberYellowstone** [comment]
未预期的错误 2
![image](https://user-images.githubusercontent.com/37031767/134762721-582601a2-e66d-4e2a-b95e-b0f4ea3b6d77.png)

**Comment by CberYellowstone** [comment]
> 未预期的错误 2
> ![image](https://user-images.githubusercontent.com/37031767/134762721-582601a2-e66d-4e2a-b95e-b0f4ea3b6d77.png)
> 
> 疑似网络波动导致的 ~ 偶发性～问题
> 已连续复现两次，且复现时间点不同，基本猜测为网络问题

这个我暂时没弄明白逻辑，留给其他人改吧（

**Comment by CberYellowstone** [comment]
顺带一提，附上一个print的输出
![image](https://user-images.githubusercontent.com/37031767/134763372-015f2c1d-7f0f-4613-b8e6-231ecce2e6b9.png)
`{'status': {'id': 1, 'type': 'wish', 'name': None}, 'rating': 0, 'comment': '', 'private': 0, 'tag': [''], 'ep_status': 0, 'vol_status': 0, 'lasttouch': 1632555228, 'user': {'id': 532595, 'url': 'http://bgm.tv/user/cbyellowstone', 'username': 'cbyellowstone', 'nickname': 'CBYellowstone', 'avatar': {'large': 'http://lain.bgm.tv/pic/user/l/000/53/25/532595.jpg?r=1619327950', 'medium': 'http://lain.bgm.tv/pic/user/m/000/53/25/532595.jpg?r=1619327950', 'small': 'http://lain.bgm.tv/pic/user/s/000/53/25/532595.jpg?r=1619327950'}, 'sign': '', 'usergroup': 10}}`

**Comment by NKID00** [comment]
其他 POST 调用的 API 返回的都是 StatusCode 数据模型就理所当然地认为管理收藏 API 也返回这个了…

**Comment by NKID00** [comment]
应该修好了，感谢反馈！！
