### ISSUE TITLE
请求添加许可证

### ISSUE THREAD

**Issue by NKID00** [wopub/Bilibili2Bangumi#2]
现在没有许可证的情况下默认由作者保留有大多数权力，甚至包括自由使用软件的权利。换句话说，目前在未经作者同意的情况下使用这个仓库也是不被允许的。
因此请求添加许可证。如果觉得太麻烦想直接放弃大多数权利的话可以考虑下 [MIT License](https://choosealicense.com/licenses/mit/)。

**Comment by nKsnC** [comment]
好的，感谢提醒
