### ISSUE TITLE
Socket 无法获取到 code

### ISSUE THREAD

**Issue by SINC-G** [wopub/Bilibili2Bangumi#5]
报错信息

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte
```

出错位置

https://github.com/wopub/Bilibili2Bangumi/blob/fd531b434980e41d4fb60e3729a366cbb06f1bba/lib/auth.py#L67

后面这个 ignore 是我加的，但忽略还是解析不到code，不知道是哪里出了问题 @CberYellowstone

**Comment by CberYellowstone** [comment]
> 报错信息
> 
> 
> ```
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte
> ```
> 
> 出错位置
> 
> https://github.com/wopub/Bilibili2Bangumi/blob/fd531b434980e41d4fb60e3729a366cbb06f1bba/lib/auth.py#L67
> 
> 后面这个 ignore 是我加的，但忽略还是解析不到 code，不知道是哪里出了问题 @CberYellowstone

你能不能print一下`data`?
看看报错时 `data` 到底返回了什么

**Comment by SINC-G** [comment]
> 看看报错时 `data` 到底返回了什么

好
```
b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03F\x1f\x97\xab\x0cvj\x1a\xed\x92\x1a\xffv\x1d>\xaa\xfasq7\x1aQ\xef\xf6i\xb9,O\x02\x10)K \xdb\x85\x85!qn\xe0\x83\xc8\x88\xd4"tSk\xcc\xa0\xb1\xee\xb7\x88\xa5\xa1\x06\xd0\x17\x05-0\x1c\x02P\x00 \n\n\x13\x01\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\xda\xda\x00\x00\x00\x00\x00\x0e\x00\x0c\x00\x00\tlocalhost\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\n\x00\x08JJ\x00\x1d\x00\x17\x00\x18\x00\x0b\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\x0c\x02h2\x08http/1.1\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\r\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00\x12\x00\x00\x003\x00+\x00)JJ\x00\x01\x00\x00\x1d\x00 F\xf9\xb7}.Y\x1d\x15\xdd\xb4 6W\x12\x04 \x99$\xcc\xb2\xd6\xc0\xf9(l\xae\x1a\xb5\xa3\x9b\x11E\x00-\x00\x02\x01\x01\x00+\x00\x0b\n\x9a\x9a\x03\x04\x03\x03\x03\x02\x03\x01\x00\x1b\x00\x03\x02\x00\x02Di\x00\x05\x00\x03\x02h2**\x00\x01\x00\x00\x15\x00\xca\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by CberYellowstone** [comment]
> > 看看报错时 `data` 到底返回了什么
> 
> 好
> 
> 
> ```
> b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03F\x1f\x97\xab\x0cvj\x1a\xed\x92\x1a\xffv\x1d>\xaa\xfasq7\x1aQ\xef\xf6i\xb9,O\x02\x10)K \xdb\x85\x85!qn\xe0\x83\xc8\x88\xd4"tSk\xcc\xa0\xb1\xee\xb7\x88\xa5\xa1\x06\xd0\x17\x05-0\x1c\x02P\x00 \n\n\x13\x01\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\xda\xda\x00\x00\x00\x00\x00\x0e\x00\x0c\x00\x00\tlocalhost\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\n\x00\x08JJ\x00\x1d\x00\x17\x00\x18\x00\x0b\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\x0c\x02h2\x08http/1.1\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\r\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00\x12\x00\x00\x003\x00+\x00)JJ\x00\x01\x00\x00\x1d\x00 F\xf9\xb7}.Y\x1d\x15\xdd\xb4 6W\x12\x04 \x99$\xcc\xb2\xd6\xc0\xf9(l\xae\x1a\xb5\xa3\x9b\x11E\x00-\x00\x02\x01\x01\x00+\x00\x0b\n\x9a\x9a\x03\x04\x03\x03\x03\x02\x03\x01\x00\x1b\x00\x03\x02\x00\x02Di\x00\x05\x00\x03\x02h2**\x00\x01\x00\x00\x15\x00\xca\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> ```

太奇怪了，这串编码完全乱掉了
你是什么浏览器？

**Comment by SINC-G** [comment]
> 你是什么浏览器？

微软的新版Edge 91

**Comment by CberYellowstone** [comment]
> > 你是什么浏览器？
> 
> 微软的新版 Edge 91

无法复现
Edge 91.0.864.48

**Comment by SINC-G** [comment]
找到问题了，我用的 https....

**Comment by CberYellowstone** [comment]
> 找到问题了，我用的 https....

那没事了..
文档写的是http (
